void OvenTimer();
void Quadrant();
void LeapYear();
void SizeComparison();
void Inputoutput();
void Variable();
void VariableTypeNumber();
void VarialeTypeCharacter();
void VariableTypeBool();
void OperationArithmetic(int Arith1, int Arinth2);
void OperationIncrementDecrement();
void OperationComparison();
void OperationLogical();
void OperationBit();
void OperationThree();
void StatementIF();
void StatementSwitch();
void StatementFor();
void StatementWhile();
int GuGuDan(int Dan);
void VarScope(int Number);
void MultipleCaculate();
void Receipt();
void Star1();
void Star2();

void DefineArray();
void TwoDimension();
void CountNumber();
void LessNumber();
void MissingNumber();
void Bubblesort();
void String();
void IndexChar();
void AlpaNumber();

void Structure();
void CallByValue();
void Enum();
